species: ecoli
data_dir: test_data
output_dir: test_output
zipped_ref_genome_filepath: test_data/ncbi_dataset.zip
zipped_gtf_filepath: test_data/ncbi_dataset_gtf.zip
sra_run: 
  filepath: SraRunTable.txt
  number_of_runs: 4
threads: 1
low: 0
high: 10000
gene: n #(y/n) -- includes gene annotations if 'y'
