name: insurveyor-env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bcftools
  - bedtools
  - bwa
  - htslib
  - insurveyor
  - numpy
  - pysam
  - samtools
  - snakemake
  - pyyaml
  - pandas