name: insurveyor-env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.6
  - aiosignal=1.3.1
  - amply=0.1.6
  - appdirs=1.4.4
  - async-timeout=4.0.3
  - attmap=0.13.2
  - attrs=23.1.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.5
  - bcftools=1.17
  - bcrypt=4.0.1
  - bedtools=2.31.1
  - boto3=1.29.0
  - botocore=1.32.0
  - brotli-python=1.1.0
  - bwa=0.7.17
  - bzip2=1.0.8
  - c-ares=1.21.0
  - ca-certificates=2023.08.22
  - cachetools=5.3.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.8
  - coin-or-utils=2.11.9
  - coincbc=2.10.10
  - colorama=0.4.6
  - configargparse=1.7
  - connection_pool=0.0.3
  - cryptography=41.0.3
  - datrie=0.8.2
  - defusedxml=0.7.1
  - docutils=0.20.1
  - dpath=2.1.6
  - dropbox=11.36.2
  - eido=0.2.1
  - exceptiongroup=1.1.3
  - filechunkio=1.8
  - frozenlist=1.4.0
  - ftputil=5.0.4
  - gdbm=1.18
  - gitdb=4.0.11
  - gitpython=3.1.40
  - google-api-core=2.14.0
  - google-api-python-client=2.108.0
  - google-auth=2.23.4
  - google-auth-httplib2=0.1.1
  - google-cloud-core=2.3.3
  - google-cloud-storage=2.13.0
  - google-crc32c=1.5.0
  - google-resumable-media=2.6.0
  - googleapis-common-protos=1.61.0
  - grpcio=1.59.2
  - gsl=2.7.1
  - h11=0.14.0
  - htslib=1.17
  - httplib2=0.22.0
  - humanfriendly=10.0
  - idna=3.4
  - importlib_resources=6.1.1
  - iniconfig=2.0.0
  - insurveyor=1.1.2
  - jinja2=3.1.2
  - jmespath=1.0.1
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_core=5.5.0
  - krb5=1.20.1
  - libabseil=20230802.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.2.0
  - libcxx=16.0.6
  - libdeflate=1.10
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgfortran5=13.2.0
  - libgrpc=1.59.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.24
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libssh2=1.11.0
  - libzlib=1.2.13
  - llvm-openmp=17.0.5
  - logmuse=0.2.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - mdurl=0.1.0
  - multidict=6.0.4
  - nbformat=5.9.2
  - ncurses=6.4
  - numpy=1.26.0
  - oauth2client=4.1.3
  - oniguruma=6.9.7.1
  - openssl=3.1.4
  - packaging=23.2
  - paramiko=3.3.1
  - peppy=0.35.7
  - perl=5.34.0
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.1
  - platformdirs=4.0.0
  - pluggy=1.3.0
  - ply=3.11
  - prettytable=3.9.0
  - protobuf=4.24.4
  - psutil=5.9.5
  - pulp=2.7.0
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyfaidx=0.7.2.2
  - pygments=2.16.1
  - pynacl=1.5.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=7.4.3
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.0
  - python-irodsclient=1.1.9
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyvcf3=1.0.3
  - pyyaml=6.0.1
  - re2=2023.06.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - reretry=0.11.8
  - rich=13.6.0
  - rpds-py=0.12.0
  - rsa=4.9
  - s3transfer=0.7.0
  - samtools=1.18
  - setuptools=68.2.2
  - setuptools-scm=8.0.4
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=6.4.0
  - smmap=5.0.0
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - stone=3.3.1
  - stopit=1.1.2
  - tabulate=0.9.0
  - throttler=1.2.2
  - tk=8.6.13
  - tomli=2.0.1
  - toposort=1.10
  - traitlets=5.13.0
  - trio=0.23.1
  - trio-websocket=0.11.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - ubiquerg=0.6.3
  - uritemplate=4.1.1
  - veracitools=0.1.3
  - wcwidth=0.2.10
  - wheel=0.41.2
  - wrapt=1.16.0
  - wsproto=1.2.0
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.9.2
  - yte=1.5.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - biopython==1.81
      - charset-normalizer==3.3.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.43.1
      - importlib-metadata==6.8.0
      - kiwisolver==1.4.5
      - libgfortran=5.0.0
      - matplotlib==3.8.0
      - munkres==1.1.4
      - outcome==1.2.0
      - pandas==2.1.1
      - pillow==9.2.0
      - pip==23.2.1
      - pyaml==23.9.7
      - tornado==6.3.3
      - unicodedata2==15.1.0
      - urllib3==1.26.17
