name: insurveyor-env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - pip
  - attrs
  - bcftools
  - bedtools
  - brotli-python
  - bwa
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - exceptiongroup
  - gsl
  - h11
  - htslib
  - idna
  - insurveyor
  - krb5
  - libblas
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - libnghttp2
  - libopenblas
  - libsqlite
  - libssh2
  - libzlib
  - llvm-openmp
  - ncurses
  - numpy
  - oniguruma
  - openssl
  - perl
  - pyfaidx
  - pysam
  - pysocks
  - python
  - python_abi
  - pyvcf3
  - readline
  - samtools
  - setuptools
  - six
  - sniffio
  - sortedcontainers
  - tk
  - trio
  - trio-websocket
  - typing_extensions
  - wsproto
  - xz
  - zlib
  - zstd
  - snakemake
  - jsonschema-specifications
  - boto3
  - platformdirs
  - traitlets
  - pygments
  - colorama
  - stopit
  - yaml
  - paramiko
  - jmespath
  - python-tzdata
  - importlib_resources
  - tabulate
  - pyasn1-modules
  - google-api-python-client
  - mdurl
  - smart_open
  - python-dateutil
  - throttler
  - google-auth
  - google-cloud-storage
  - pluggy
  - pytz
  - cachetools
  - libprotobuf
  - uritemplate
  - appdirs
  - smmap
  - veracitools
  - grpcio
  - cryptography
  - pyasn1
  - filechunkio
  - gitpython
  - rsa
  - pycparser
  - rich
  - jinja2
  - requests
  - cffi
  - google-cloud-core
  - libcrc32c
  - ftputil
  - setuptools-scm
  - multidict
  - slacker
  - charset-normalizer
  - reretry
  - pyyaml
  - coin-or-cbc
  - pytest
  - nbformat
  - packaging
  - pyparsing
  - stone
  - ply
  - google-resumable-media
  - peppy
  - oauth2client
  - gitdb
  - prettytable
  - coin-or-cgl
  - httplib2
  - python-fastjsonschema
  - defusedxml
  - pynacl
  - pkgutil-resolve-name
  - yte
  - zipp
  - snakemake-minimal
  - pandas
  - docutils
  - jupyter_core
  - aiohttp
  - referencing
  - logmuse
  - jsonschema
  - markupsafe
  - psutil
  - libre2-11
  - google-crc32c
  - wrapt
  - dropbox
  - async-timeout
  - protobuf
  - s3transfer
  - humanfriendly
  - backports
  - datrie
  - connection_pool
  - pysftp
  - iniconfig
  - wheel
  - re2
  - googleapis-common-protos
  - toposort
  - tomli
  - amply
  - markdown-it-py
  - urllib3
  - python-irodsclient
  - libsodium
  - coin-or-utils
  - libabseil
  - plac
  - coin-or-osi
  - google-api-core
  - yarl
  - dpath
  - tzdata
  - coin-or-clp
  - backports.functools_lru_cache
  - wcwidth
  - rpds-py
  - aiosignal
  - attmap
  - liblapacke
  - pyopenssl
  - coincbc
  - typing-extensions
  - ubiquerg
  - bcrypt
  - google-auth-httplib2
  - configargparse
  - eido
  - aioeasywebdav
  - frozenlist
  - botocore
  - pulp
  - pyu2f
  - libgrpc
